### ISSUE TITLE
Server Host Software Installation and Configuration

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#14]
### Description
The initial software installation and configuration. Including configuration of the hardware and Operating System that will be running on the Server.

### To-Do
- [ ] Configure the Server BIOS Settings.
- [ ] Install the Operating System.
- [ ] Configure the Docker Host (Server) to use Docker and Docker Compose [^1]
- [ ] Create the Directory and File Structure for the Docker Container Files
- [ ] Secure the Linux Operating System
- [ ] Configure the Server on the Network
- [ ] Setup the domain to point to the Server (for remote access)
