### ISSUE TITLE
A.I Object Detection Software

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#19]
### Description
Create a Docker Compose file and other configuration files for the Cuda Toolkit that will be used for processing data, using TensorFlow.

### Application Used
Cuda Toolkit from NVIDIA[^1].

NOTE: Might be able to use a custom image of Frigate, designed for using an NVIDIA GPU for this.

### To-Do
- [ ] Create and Configure the Docker Compose Yaml File
- [ ] Create and Configure the Environment Variable file, specific for the container application
- [ ] Configure the Toolkit to use the GPU within the container (passthrough)
- [ ] Deploy and Test the Container

[^1]: [Cuda Toolkit Documentation](https://docs.nvidia.com/cuda)
