### ISSUE TITLE
Authentication Software

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#20]
### Description
Secure remote access to the Server, using Google OAuth for authentication. Allowing access to the Dashboard and Apps after successfully authenticating. Simple setup using a Google Account, and only allowing access using an Access Control List (ACL).

### Application Used
Traefik-Forward-Auth (Google OAuth)

### To-Do
- [ ] Create and Configure the Docker Compose Yaml File
- [ ] Create and Configure the Environment Variable file, specific for the container application
- [ ] Configure Google OAuth for Multi-Factor Authentication (MFA)

[^1]: [Authentication Documentation]()
