### ISSUE TITLE
Intrusion Prevention Software

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#21]
### Description
Create a Docker Compose file and other configuration files for the Intrusion Detection and Prevention and deploy the container on the Server.

### Application Used
Crowdsec[^1].

### To-Do
- [ ] Create and configure the Docker Compose Yaml File
- [ ] Create and Configure the Environment Variable file, specific for the container application
- [ ] Deploy and Test the Container

[^1]: [Crowdsec Documentation](https://doc.crowdsec.net/)
