### ISSUE TITLE
Reverse-Proxy Software

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#22]
### Description
Open-Source Application Proxy that makes publishing services easy. It receives requests on behalf of the systems and identifies which components are responsible for handling them, then routes them securely.

### Application Used
Traefik Reverse-Proxy[^1]

### To-Do
- [ ] Create and Configure the Docker Compose Yaml File
- [ ] Create and Configure the Environment Variable file, specific for the container application
- [ ]  Configure the Dynamic Configuration files to integrate with the other container apps for routing
- [ ] Deploy and Test the Container

[^1]: [Traefik Documentation](https://docs.traefik.io/traefik)
