### ISSUE TITLE
Dashboard Software

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#24]
### Application Used
Homepage Dashboard[^1]

### To-Do
- [ ] Create and Configure the Docker Compose Yaml File
- [ ] Create and Configure the Environment Variable file, specific for the container application
- [ ] Configure the Dashboard, which will be the landing page for users after successfully authenticating.
- [ ] Add Widgets to the Dashboard for each container app that has a web ui
- [ ] Add Monitor Widgets to show the status of the Server
- [ ] Deploy and Test the Container

[^1]: [Homepage Documentation](https://gethomepage.dev/latest/configs)
