### ISSUE TITLE
Administrator Tools Software

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#25]
### Description
A collection of handy online tools for developers and people working in IT. Tools that boost productivity, perform conversions, and help with development.

### Application Used
IT-Tools[^1]

### To-Do
- [ ] Create and configure the Docker Compose Yaml File
- [ ] Create and Configure the Environment Variable file, specific for the container application
- [ ] Configure the IT-Tools for Admin tasks specific to the NVR System
- [ ] Deploy and Test the Container

[^1]: [IT-Tools Documentation](https://github.com/CorentinTh/it-tools)
