### ISSUE TITLE
Logging Software

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#26]
### Description
An Open-Source Log Viewer designed to simplify the process of monitoring and debugging Docker Containers. Provides a web UI with real-time log streaming, filtering, and searching capabilities.

### Application Used
Dozzle[^1]

### To-Do
- [ ] Create and Configure the Docker Compose Yaml File
- [ ] Create and Configure the Environment Variable file, specific for the container application
- [ ] Configure the logging for each of the containers running on the NVR System
- [ ] Deploy and Test the Container

[^1]: [Dozzle Documentation](https://dozzle.dev/guide/getting-started)
