### ISSUE TITLE
MQTT Broker Software

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#27]
### Description
An Open-Source message broker that implements the MQTT protocol [^1]. Mosquitto is lightweight and suitable for use on all devices from a low power single board computer to full servers.

### Application Used
Mosquitto MQTT Broker[^2]

### To-Do
- [ ] Create and configure the Docker Compose Yaml File
- [ ] Create and Configure the Environment Variable file, specific for the container application
- [ ] Setup to integrate Frigate NVR and Home Assistant to communicate
- [ ] Deploy and Test the Container

[^1]: [MQTT Protocol Information](https://mqtt.org/mqtt-specification)
[^2]: [MQTT Broker Documentation](https://mosquitto.org/documentation)
