### ISSUE TITLE
Automation Software

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#28]
### Description
Open-Source Automation software that puts local control and privacy first. Providing integrations with a multitude of applications and devices.

### Application Used
Home Assistant[^1]

### To-Do
- [ ] Create and Configure the Docker Compose Yaml File
- [ ] Create and Configure the Environment Variable file, specific for the container application
- [ ] Configure Home Assistant to use the MQTT Broker to communicate with the NVR Software
- [ ] Deploy and Test the Container

[^1]: [Home Assistant Documentation](https://home-assistant.io/docs)
