### ISSUE TITLE
Root Compose Files

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#29]
### Description
Create the "root" Docker Compose yaml file and Environment Variables files, these are what will be used to link all the container app specific compose and environment variable files, as well as configuring the secret files, and the Docker network configuration.
### To-Do
- [ ] Create the "root" compose.yml and .env files
- [ ] Add the Docker Network Configuration, Secret File paths, and Includes section that point to the container app compose and env files
- [ ] Add the general environment variables that will be used throughout all of the Docker Compose files, to prevent repeating information
