### ISSUE TITLE
Bash Aliases

### ISSUE THREAD

**Issue by G33kman** [G33kman/NVR-Server#30]
### Description
The Bash Aliases file will be used to create easy to remember command shortcuts to make working in the terminal easier.
For instance, creating an alias such as "sdcu" could be set to run the command "sudo docker compose up -d" command.

### To-Do
- [ ] Create the bash aliases file
- [ ] Determine what commands will be included initially, without bloating the file
- [ ] Move the file to the home directory and source it so that it is available in the terminal
- [ ] Review the file when the project is completed, to remove any aliases that won't be needed anymore
